markdown: kramdown
title: MikroORM
theme: jekyll-theme-cayman
permalink: pretty

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
  auto_ids: true
  toc_levels: 2..4

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

sass:
  style: compressed
  sass_dir: _assets

defaults:
  -
    scope:
      path: '' # an empty string here means all files in the project
    values:
      layout: 'default'
